// Generated by https://quicktype.io

export interface IngredientesResponse {
    status:  number;
    message: string;
    data:    Ingrediente[];
}

export interface Ingrediente {
    id:          number;
    ingrediente: string;
    descripcion: string;
    activo:      number;
    restringido: number;
    estadosId:   number;
    estado:      string;
}
