// Generated by https://quicktype.io

export interface ProductosResponse {
    status:  number;
    message: string;
    data:    Producto[];
}

export interface ProductoResponse {
    status:  number;
    message: string;
    data:    Producto;
}
export interface Producto {
    id:                  number;
    producto:            string;
    descripcion:         string;
    tipo_productosId:    number;
    usuarioCreacion:     string;
    fechaCreacion:       string;
    fechaActualizacion?: string;
    estadosId:           number;
}
