// Generated by https://quicktype.io

export interface ProductoRequest {
    producto:         string;
    descripcion:      string;
    tipo_productosId: number;
    usuarioCreacion:  string;
    estadosId:        number;
}

export interface ProductoModRequest {
    producto:         string;
    descripcion:      string;
    tipo_productosId: number;
    usuarioCreacion:  string;
    usuarioActualizacion:  string;
    estadosId: number;
}