// Generated by https://quicktype.io

export interface LoginResponse {
    status:  number;
    message: string;
    data:    Data;
}

export interface Data {
    email:  string;
    tokens: Tokens;
}

export interface Tokens {
    refresh: string;
    access:  string;
}
