// Generated by https://quicktype.io

export interface LoginResponse {
    status:  number;
    message: string;
    data:    Data;
}

export interface Data {
    id:        number;
    usuario:   string;
    nombres:   string;
    apellidos: string;
    pass:      string;
    rol:       number;
    estadoId:  number;
    token:     string;
}
